# Install environment for dev
#
# Create image :
# $ sudo docker.io build -t ubuntu:simplenote - < dockerfile
# $ sudo docker.io run ubuntu:simplenote -v ./src/:/var/www
# VERSION 1.0

FROM ubuntu:latest
MAINTAINER Maxime Raynal - <me@maxproject.fr>

#EXPOSE 80:8081

# Make sure the package repository is up to date
ADD sources.list /etc/apt/sources.list
RUN apt-get -y update

# Install prerequirement
RUN apt-get install -y --force-yes nginx php5-sqlite php5-cli vim php5-fpm curl --fix-missing

RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer

RUN mkdir /var/www/

RUN chown -R www-data:www-data /var/www

ADD symfony.nginx-config /etc/nginx/sites-available/symfony

RUN ln -s /etc/nginx/sites-available/symfony /etc/nginx/sites-enabled/symfony
RUN rm /etc/nginx/sites-enabled/default

ADD setup.sh /root/setup.sh
RUN chmod u+x /root/setup.sh

ENTRYPOINT ["/root/setup.sh"]
