# Install environment for dev
#
# Create image :
# $ sudo docker.io build -t ubuntu:simplenote_develop - < dockerfile
# $ sudo docker.io run ubuntu:simplenote_develop -v ./src/:/var/www
# VERSION 1.0

FROM ubuntu:latest
MAINTAINER Maxime Raynal - <me@maxproject.fr>

#EXPOSE 80:8081

# Make sure the package repository is up to date
RUN echo 'deb http://ppa.launchpad.net/nginx/stable/ubuntu trusty main' >> /etc/apt/sources.list
RUN echo 'deb-src http://ppa.launchpad.net/nginx/stable/ubuntu trusty main' >> /etc/apt/sources.list
RUN apt-get -y update

# Install prerequirement
RUN apt-get install -y --force-yes nginx php5 vim php5-fpm

RUN mkdir /var/www/

RUN chown www-data:www-data /var/www

ADD simplenote-dev.nginx-config /etc/nginx/sites-available/simplenote-dev

RUN ln -s /etc/nginx/sites-available/simplenote-dev /etc/nginx/sites-enabled/simplenote-dev
RUN rm /etc/nginx/sites-enabled/default