simple_note_notesList:
    path:     /notes.{_format}
    defaults: { _controller: SimpleNoteNoteBundle:Note:notesList }
    methods: GET
    requirements:
        _format: json

simple_note_tagsList:
    path:     /tags.{_format}
    defaults: { _controller: SimpleNoteNoteBundle:Note:tagsList }
    methods: GET
    requirements:
        _format: json

simple_note_noteById:
    path: /note/id-{id}.{format}
    defaults: { _controller: SimpleNoteNoteBundle:Note:noteById }
    methods: GET
    requirements:
        id: \d+
        format: json