parameters:
    pageLoader.class: SimpleNote\NoteBundle\Service\PageLoader
    pageLoader.basePath: "/root"

services:
    pageLoader:
        class: "%pageLoader.class%"
        arguments: ["%pageLoader.basePath%"]
