parameters:
#    simple_note_note.example.class: SimpleNote\NoteBundle\Example

services:
#    simple_note_note.example:
#        class: %simple_note_note.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
