parameters:
    PageLoader.class: SimpleNote\NoteBundle\Service\PageLoader
    PageLoader.basePath: "/var/www/app/data/"

services:
    PageLoader:
        class: "%PageLoader.class%"
        arguments: ["%PageLoader.basePath%"]
