security:
    providers:
        in_memory:
            memory:
                users:
                    test: { password: test, roles: 'ROLE_USER'}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern: ^/
            anonymous: ~
            http_basic:
                realm: "Authentification requise"
    access_control:
        - { path: ^/, roles: ROLE_USER }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext